# GitHub Environment Configuration for NPM Publishing
# This file serves as documentation for the required environment setup
# 
# To configure this environment in GitHub:
# 1. Go to Settings > Environments
# 2. Create new environment named "npm-publish"
# 3. Add the following secrets:
#    - NPM_TOKEN: Your NPM automation token
# 4. Configure protection rules as needed

name: npm-publish
description: Environment for publishing packages to NPM

# Protection rules (configure in GitHub UI):
# - Required reviewers: Add team members who can approve releases
# - Wait timer: Optional delay before deployment
# - Deployment branches: Restrict to main branch only

# Required secrets:
secrets:
  - name: NPM_TOKEN
    description: NPM automation token with publish permissions
    required: true

# Required variables (if any):
variables: []

# Environment URL (will be set to NPM package URL after first publish)