/**
 * @fileoverview Expo config plugin for @bearound/react-native-sdk.
 *
 * Everything the SDK needs on top of autolinking is native project configuration —
 * background modes, BGTask identifiers, usage strings, entitlements and the
 * AppDelegate wiring. Under Expo's Continuous Native Generation those files are
 * regenerated by `expo prebuild`, so hand edits do not survive. This plugin applies
 * them on every prebuild instead.
 *
 * ```json
 * { "expo": { "plugins": [["@bearound/react-native-sdk", { "backgroundWifi": true }]] } }
 * ```
 *
 * What it does NOT do (and cannot): grant on-device permissions, create the Apple
 * push key, or file the Google Play foreground-service declaration.
 */

const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withAppDelegate,
  withEntitlementsPlist,
  withInfoPlist,
} = require('@expo/config-plugins');

const { withBearoundAppDelegate } = require('./appDelegate');

const pkg = require('../package.json');

const BACKGROUND_MODES = [
  'bluetooth-central',
  'fetch',
  'location',
  'processing',
  'remote-notification',
];

const BGTASK_IDENTIFIERS = [
  'io.bearound.sdk.sync',
  'io.bearound.sdk.processing',
];

/**
 * Defaults are deliberately generic. They are what YOUR users read in the iOS
 * permission dialog, and Apple reviews the wording against what the app does — so
 * override them with app-specific copy via the plugin props or `ios.infoPlist`.
 */
const DEFAULT_USAGE_DESCRIPTIONS = {
  NSBluetoothAlwaysUsageDescription:
    'This app uses Bluetooth to detect nearby locations and provide relevant features.',
  NSBluetoothPeripheralUsageDescription:
    'This app uses Bluetooth to detect nearby locations and provide relevant features.',
  NSLocationWhenInUseUsageDescription:
    'This app uses your location to detect nearby locations and provide relevant features.',
  NSLocationAlwaysAndWhenInUseUsageDescription:
    'Allow "Always" so this app can detect nearby locations in the background.',
};

const union = (current, additions) =>
  Array.from(
    new Set([...(Array.isArray(current) ? current : []), ...additions])
  );

const withBearoundInfoPlist = (config, props) =>
  withInfoPlist(config, (cfg) => {
    const plist = cfg.modResults;

    plist.UIBackgroundModes = union(plist.UIBackgroundModes, BACKGROUND_MODES);
    plist.BGTaskSchedulerPermittedIdentifiers = union(
      plist.BGTaskSchedulerPermittedIdentifiers,
      BGTASK_IDENTIFIERS
    );

    const descriptions = {
      ...DEFAULT_USAGE_DESCRIPTIONS,
      ...(props.usageDescriptions ?? {}),
    };
    for (const [key, value] of Object.entries(descriptions)) {
      // Never overwrite what the app already declares — app.json/app.config wins.
      if (!plist[key]) plist[key] = value;
    }

    // Without this key iOS never shows the App Tracking Transparency prompt, so
    // the SDK reports no advertising identifier — silently, with no error.
    if (props.trackingUsageDescription) {
      plist.NSUserTrackingUsageDescription = props.trackingUsageDescription;
    }

    return cfg;
  });

const withBearoundEntitlements = (config, props) =>
  withEntitlementsPlist(config, (cfg) => {
    // The connected access point is invisible to iOS apps without this entitlement.
    // Nothing errors — the field is simply never reported.
    if (props.wifiInfo !== false) {
      cfg.modResults['com.apple.developer.networking.wifi-info'] = true;
    }

    // Silent push is the only vector that wakes a force-quit app. EAS Build
    // rewrites the value to `production` for release builds; a bare
    // `expo run:ios` keeps `development` (sandbox APNs).
    if (props.apsEnvironment !== false) {
      cfg.modResults['aps-environment'] =
        props.apsEnvironment ??
        cfg.modResults['aps-environment'] ??
        'development';
    }

    return cfg;
  });

const withBearoundAndroidPermissions = (config, props) => {
  // The native SDK declares every scan permission itself and the manifest merger
  // injects them. The one exception is background location: it is not a scan
  // requirement, it is what keeps Wi-Fi observations alive once the app is
  // backgrounded, and it carries a Play policy review — so it is opt-in.
  if (!props.backgroundWifi) return config;

  return withAndroidManifest(config, (cfg) => {
    AndroidConfig.Permissions.ensurePermissions(cfg.modResults, [
      'android.permission.ACCESS_BACKGROUND_LOCATION',
    ]);
    return cfg;
  });
};

const withBearoundIosAppDelegate = (config, props) => {
  if (props.appDelegate === false) return config;

  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[bearound] expected a Swift AppDelegate, got "${cfg.modResults.language}". ` +
          'BeAroundSDK is pure Swift and cannot be called from Objective-C.'
      );
    }
    cfg.modResults.contents = withBearoundAppDelegate(cfg.modResults.contents);
    return cfg;
  });
};

/**
 * @param {import('@expo/config-types').ExpoConfig} config
 * @param {object} [props]
 * @param {boolean} [props.backgroundWifi=false] Declare `ACCESS_BACKGROUND_LOCATION`
 *   on Android. Wi-Fi observations are collected by default, but only while the app
 *   is on screen; this is what keeps them coming in the background. Costs a Google
 *   Play policy review. Beacon detection never needs it.
 * @param {boolean} [props.wifiInfo=true] Add the iOS Access WiFi Information entitlement.
 * @param {'development'|'production'|false} [props.apsEnvironment] APNs environment,
 *   or `false` to leave the entitlement alone.
 * @param {Record<string,string>} [props.usageDescriptions] Override the `NS…UsageDescription`
 *   strings your users read in the permission dialogs.
 * @param {string} [props.trackingUsageDescription] Enables the App Tracking Transparency
 *   prompt (required for the advertising identifier).
 * @param {boolean} [props.appDelegate=true] Set to `false` to skip the AppDelegate
 *   wiring — background and terminated-state detection stop working.
 */
const withBearound = (config, props = {}) => {
  config = withBearoundInfoPlist(config, props);
  config = withBearoundEntitlements(config, props);
  config = withBearoundIosAppDelegate(config, props);
  config = withBearoundAndroidPermissions(config, props);
  return config;
};

module.exports = createRunOncePlugin(withBearound, pkg.name, pkg.version);
