// @generated by RN Codegen — você edita este arquivo
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';

export type Beacon = {
  uuid: string;
  major: string;
  minor: string;
  rssi: number;
  bluetoothName?: string;
  bluetoothAddress?: string;
  distanceMeters?: number;
};

export interface Spec extends TurboModule {
  initialize(clientToken: string, debug?: boolean): Promise<void>;
  stop(): Promise<void>;

  // Obrigatório para EventEmitter no Android
  addListener(eventName: string): void;
  removeListeners(count: number): void;
}

export default TurboModuleRegistry.getEnforcing<Spec>('BearoundReactSdk');
